Związek Dawniejszych Powstańców na rzecz Górnośląskiej Niepodległości
Związek Dawniejszych Powstańców na rzecz Górnośląskiej Niepodległości – organizacja działająca na terenie Prowincji Górnośląskiej w latach 1921-1922 w granicach Niemiec , składała się z byłych powstańców śląskich , dążyła pierwotnie do niepodległości Górnego Śląska , następnie do autonomii Górnego Śląska , jako państwa związkowego Rzeszy , ostatecznie do autonomii Prowincji Górnośląskiej , pozostałej po podziale Górnego Śląska w państwie niemieckim .
Działalność .
Związek Dawniejszych Powstańców na rzecz Górnośląskiej Niepodległości ( Bund der ehemäligen Insurgenten für oberschlesische Selbständigkeit ) został założony 5 sierpnia 1921 roku przez Franciszka Merika – byłego dowódcę frontowego z Opola , który podczas III powstania był jednym z tych dowódców , którzy domagali się od Wojciecha Korfantego proklamacji `` suwerennego państwa śląskiego '' .
Organizacja wykorzystała fakt , że Wojsko Polskie i Reichswehra nie zajęły jeszcze podzielonego terytorium plebiscytowego .
Kolportowała ulotki nawołujące do przewrotu i ustanowienia niepodległości Górnego Śląska .
Inicjatywę tę storpedowali stronnicy Korfantego .
Ugrupowanie to poszło śladami również stworzonego przez powstańców Polskiego Związku Górnośląskich Autonomistów – Alojzego Pronobisa .
17 marca 1922 roku Jan Kustos utworzył Śląskie Stronnictwo Demokratyczno-Postępowe , za którego pomocą chciał się dostać w szeregi Naczelnej Rady Ludowej Górnego Śląska .
Zgodnie z relacją `` Rzeczpospolitej '' zatytułowanej `` Przygotowania do zamachu na Górnym Śląsku '' , opartej na relacji Wyglendy , gdy Janowi Kustosowi nie udało się legalnie dostać do NRL , postanowił opanować ją siłą .
Stanowisko Józefa Rymera miało być przeznaczone mjr Ludwikowi Hupce , jako śląskiemu dyktatorowi wojskowemu .
Lider Związku Dawniejszych Powstańców na rzecz Górnośląskiej Niepodległości ( Bund der ehemäligen Insurgenten für oberschlesische Selbständigkeit ) – Franciszek Merik miał zapewnić potrzebne oddziały zbrojne .
Po opanowaniu gmachu Naczelnej Rady Ludowej Górnego Śląska , zamachowcy mieli wszystkich nie-Górnoślązaków odstawić do granicy i postawić władze Rzeczypospolitej Polskiej przed faktem dokonanym .
Idea ta zyskała sporą popularność wśród powstańców , niezadowolonych z coraz większych wpływów na Górnym Śląsku , osiąganych przez przedsiębiorców , urzędników i wojskowych , pochodzących z Polski .
Inicjatywa Franciszka Merika została jednak skutecznie storpedowana przez obóz Korfantego , z którego polecenia zebranie Związku Dawniejszych Powstańców na rzecz Górnośląskiej Niepodległości ( Bund der ehemäligen Insurgenten für oberschlesische Selbständigkeit ) zostało rozbite przez wierny Polsce oddział powstańców z Pszczyny pod dowództwem Stanisława Krzyżowskiego .
Działania Jana Kustosa i Franciszka Merika miała koordynować , stworzona przez szeroką rzeszę byłych powstańców ( m.in .
Polski Związek Górnośląskich Autonomistów – Alojzego Pronobisa i katowicki oddział Związku Byłych Powstańców – Walentego Fojkisa ) i działaczy obozu polskiego , Liga Obrony Górnego Śląska ( Liga zum Schutz Oberschlesiens ) .
Jej liderzy powołali do życia własną 40-osobową Radę Ludową , która usiłowała przeforsować nadanie całemu terytorium plebiscytowemu na Górnym Śląsku bardzo szerokiej autonomii politycznej , gospodarczej i kulturowej .
Nie determinowała ona przy tym , czy ma się tu urzeczywistnić w ramach związku , z którymś z dwu rywalizujących państw , czy też w formie „ autonomii zupełnej ” ( niepodległość ) pod protektoratem aliantów .
Wojciech Korfanty natychmiast zlikwidował rozłam w polskim obozie , odcinając Radę Ludową od funduszy .
Dążenia Franciszka Merika do przewrotu są niewątpliwym faktem , natomiast Jan Kustos i mjr Ludwik Hupka protestowali przeciwko relacjom Wyglendy .
Józef Rymer chwalił Wyglendę za udaremnienie przewrotu , jednak nie wiadomo ile prawdy było w jego doniesieniach .
Związek Dawniejszych Powstańców na rzecz Niepodległości Górnego Śląska ( Bund der ehemäligen Insurgenten für oberschlesische Selbständigkeit ) skierował do przewodniczącego konferencji pokojowej de Facty pismo protestacyjne przeciwko `` polskiej działalności terrorystycznej na Górnym Śląsku '' .
Natomiast jego lider Franciszek Merik nie dał za wygraną , zmieniając opcję z niepodległościowej na autonomistyczną , opowiedział się za zmianą orzeczenia z Genewy , publicznie oświadczając , „ że całe byłe terytorium plebiscytowe musi otrzymać pełną autonomię w federacyjnym związku państwowym z Niemcami ” .
22 czerwca 1922 roku Wojsko Polskie i Reichswehra objęły podzielone terytorium plebiscytowe .
Województwo śląskie w ramach Rzeczypospolitej Polskiej , zgodnie z zapisami Statutu Organicznego , uchwalonego podczas kampanii plebiscytowej 20 lipca 1920 roku otrzymało szeroką autonomię gospodarczą i fiskalną ( Skarb Śląski ) oraz ograniczoną ( wojewoda z nominacji prezydenta RP ) autonomię polityczną z własnym parlamentem ( Sejmem Śląskim ) .
Kwestię autonomii Prowincji Górnośląskiej w ramach Rzeszy Niemieckiej ( republiki weimarskiej ) miało rozstrzygnąć referendum zorganizowane w dniu 22 września 1922 roku .
18 września na zjeździe w Prudniku liderzy Katholische Volkspartei pod przewodnictwem Carla Ulitzki , opowiadający się dotychczas za przekształceniem Prowincji Górnośląskiej w autonomiczne państwo związkowe Rzeszy Niemieckiej , stwierdzili iż wskutek podziału terytorium plebiscytowego oraz ugody z władzami Prus , okrojona „ Prowincja Górnośląska powinna pozostać w pruskim związku państwowym ” .
6 września 1922 roku poglądy Carla Ulitzki podzielił również przewodniczący Związku Byłych Powstańców na rzecz Górnośląskiej Niepodległości ( Bund der ehemäligen Insurgenten für oberschlesische Sebständigkeit ) – Franciszek Merik w liście do pruskiego ministra spraw wewnętrznych Carla Severinga napisał : `` Jak jeszcze na naszej pieczątce widać , związek składa się wyłącznie z członków niegdyś polskiego usposobienia .
Podstawowym celem związku jest osiągnięcie federacyjno-państwowej autonomii Górnego Śląska [ … ] Skoro jednak rząd pruski sam błąd zauważył i nas Górnoślązaków ma bronić ustawą administracyjną , odstępujemy od naszych federacyjno-państwowych dążeń i przyłączamy się do deklaracji posła Rzeszy – pana proboszcza Ulitzki na rzecz pozostania Górnego Śląska przy Prusach .
Będziemy stać na straży pruskich interesów i zwalczać polską propagandę z Kongresówki '' .
Wkrótce Franciszek Merik wydał odezwę do swych rodaków : `` My byli powstańcy z ofiarą naszego życia , walczyliśmy za wasze dążenia i będziemy to czynić nadal .
Dlatego obdarzcie nas zaufaniem i bez wyjątku odrzućcie karty do głosowania zgodnie z hasłem : Górny Śląsk musi pozostać pruską prowincją . ''
Taki jednolity front spowodował , że podczas referendum 91 % Górnoślązaków opowiedziało się przeciwko wyłączeniu Prowincji Górnośląskiej z Prus i przekształceniu jej w odrębny kraj związkowy Rzeszy .
