Florentynów ( gromada )
Florentynów – dawna gromada , czyli najmniejsza jednostka podziału terytorialnego Polskiej Rzeczypospolitej Ludowej w latach 1954–1972 .
Gromady , z gromadzkimi radami narodowymi ( GRN ) jako organami władzy najniższego stopnia na wsi , funkcjonowały od reformy reorganizującej administrację wiejską przeprowadzonej jesienią 1954 do momentu ich zniesienia z dniem 1 stycznia 1973 , tym samym wypierając organizację gminną w latach 1954–1972 .
Gromadę Florentynów siedzibą GRN we Florentynowie utworzono – jako jedną z 8759 gromad na obszarze Polski – w powiecie łęczyckim w woj .
łódzkim , na mocy uchwały nr 32/54 WRN w Łodzi z dnia 4 października 1954 .
W skład jednostki weszły obszary dotychczasowych gromad Bardzynin i Huta Bardzyńska ze zniesionej gminy Dalików oraz obszary dotychczasowych gromad Nowe Młyny i Florentynów , a także kolonia Ignacew Folwarczny i kolonia Gołaszyny z dotychczasowej gromady Ignacew , kolonia Ignacew Podleśny z dotychczasowej gromady Ignacew Rozlazły oraz wieś Nowa Jerozlima z dotychczasowej gromady Mikołajew ze zniesionej gminy Parzęczew w tymże powiecie .
Dla gromady ustalono 10 członków gromadzkiej rady narodowej .
1 stycznia 1958 z gromady Florentynów wyłączono wieś i kolonię Bardzynin oraz wsie Ostrów , Witów , Włodzimierzów , Karolinów i Emilianów , włączając je do gromady Dalików w powiecie poddębickim .
1 stycznia 1959 z gromady Florentynów wyłączono wsie Huta Bardzyńska , Eufemia , Simonia i Rozynów oraz kolonię Rozynów – włączając je do gromady Dalików w powiecie poddębickim , po czym gromadę Florentynów zniesiono , a jej ( pozostały ) obszar włączono do gromad : Chociszew ( kolonię Nowa Jerozolima , wieś Nowe Młyny , wieś Sokola Góra , wieś Mariampol , osadę Smolarnia , wieś Florentynów , wieś Anastazew i wieś Gortatów ) i Parzęczew ( kolonię Gołaszyny , wieś Ignacew Folwarczny i wieś Ignacew Podleśny ) w powiecie łęczyckim .
